apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-demo

resources:
  - 01_kustomize_demoapp_ns.yaml
  - 02_kustomize_demoapp_dep.yaml
  - 03_kustomize_svc.yaml

namePrefix: kustomize-

commonLabels:
  env: development
